### ISSUE TITLE
Be able to get the raw (un-decoded) token

### ISSUE THREAD

**Issue by walro** [twingly/rack-indicium#8]
WDYT of adding `jwt.raw`? I have a case where I'd just like to pass the token to a subsystem without having to encode it again.

**Comment by dentarg** [comment]
So something like this

```ruby
token = env.fetch("jwt.raw") { nil }
```

that do does this for you

```ruby
authorization = env['HTTP_AUTHORIZATION']
return nil if authorization.nil?
token = authorization.split(' ').last
```

Right?

**Comment by walro** [comment]
> So something like this

Yes

> that does this for you

Kind of, implementation has changed here (regexp based etc), but the gist of it, yes. :)

**Comment by jage** [comment]
> WDYT of adding jwt.raw?

Sure
